### ISSUE TITLE
(feature request) adding ability to restore exported object

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [random-geek/meshport#10]
imagine that due to reasons you need to move between desktop minetest and mobile minetest. 
just thought that it could be possible to store information of mesh to be used inside that tool so it can restore region in obj format same way as worldedit does to minetest exports... 
idk if possible, just giving idea :)

**Comment by random-geek** [comment]
I hope I understand you correctly. The generated .obj files don't currently contain any node information, so that would need to be added to the file exporter code. However, I don't see a benefit in adding this feature as it would be somewhat difficult to implement, and WorldEdit already has similar functionality. As such, I'm closing this for now.

Thanks for the suggestion!

**Comment by hacknorris-aka-penguin** [comment]
ok, understood too
